"""create task events

Revision ID: 0b329e7fd91b
Revises: fb3505825719
Create Date: 2026-09-25 04:47:21.289138

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b329e7fd91b"
down_revision: str | Sequence[str] | None = "fb3505825719"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "CREATED",
                "ASSIGNED",
                "STATUS_CHANGED",
                "OVERDUE",
                "COMPLETED",
                name="task_event_type",
            ),
            nullable=False,
        ),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_task_events_task_event_type",
        "task_events",
        ["task_id", "event_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_task_events_task_event_type", table_name="task_events")
    op.drop_table("task_events")
    # ### end Alembic commands ###
