"""create tasks and task events

Revision ID: ce8b5c3412ab
Revises: 0b329e7fd91b
Create Date: 2026-09-25 16:08:29.575850

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "ce8b5c3412ab"
down_revision: str | Sequence[str] | None = "0b329e7fd91b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
